apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  # 볼륨의 용량
  capacity:
    storage: 2Gi
  # 볼륨을 파일 시스템 형식으로 설정
  volumeMode: Filesystem
  # 볼륨의 읽기/쓰기 옵션을 설정
  accessModes:
  - ReadWriteOnce
  # 스토리지 클래스를 설정
  storageClassName: manual
  # PersistentVolume이 더 이상 사용되지 않을 때 정책을 설정한다.
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /Users/jin605/k8s-data/mariadb